<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: sans-serif; color: #111; font-size: 13px; }
    h1 { font-size: 20px; margin-bottom: 0; }
    .subtitle { color: #666; margin-top: 4px; }
    .section { margin-top: 24px; }
    .section h2 { font-size: 15px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    td, th { text-align: left; padding: 4px 8px 4px 0; border-bottom: 1px solid #eee; }
    .disclaimer { margin-top: 32px; font-size: 10px; color: #999; }
    .zone-abnormal { color: #b91c1c; font-weight: bold; }
    .zone-borderline { color: #92400e; }
</style>
</head>
<body>
    <h1>Health Summary — {{ $member->display_name }}</h1>
    <div class="subtitle">
        {{ $member->gender ? ucfirst($member->gender) : '' }}
        @if($member->date_of_birth) &middot; DOB {{ $member->date_of_birth->toFormattedDateString() }} @endif
        @if($member->blood_group) &middot; Blood group {{ $member->blood_group }} @endif
    </div>

    <div class="section">
        <h2>Active conditions &amp; allergies</h2>
        @if($conditions->isEmpty())
            <p>None on record.</p>
        @else
            <table>
                @foreach($conditions as $condition)
                    <tr>
                        <td>{{ $condition->title ?: ucfirst(str_replace('_', ' ', $condition->category)) }}</td>
                        <td>{{ $condition->category === 'allergy' ? 'Allergy' : 'Chronic condition' }}</td>
                        <td>{{ $condition->record_date?->toFormattedDateString() }}</td>
                    </tr>
                @endforeach
            </table>
        @endif
    </div>

    <div class="section">
        <h2>Recent vitals (last 90 days)</h2>
        @if($latestVitals->isEmpty())
            <p>No vitals logged in this period.</p>
        @else
            <table>
                @foreach($latestVitals as $vital)
                    <tr>
                        <td>{{ str_replace('_', ' ', $vital['vital_type']) }}</td>
                        <td class="zone-{{ $vital['zone'] }}">{{ $vital['value'] }} {{ $vital['unit'] }}</td>
                        <td>{{ $vital['recorded_at']->toFormattedDateString() }}</td>
                    </tr>
                @endforeach
            </table>
        @endif
    </div>

    <p class="disclaimer">
        Generated by HealthSync on {{ $generatedAt->toDayDateTimeString() }}. This summary is for informational
        purposes only and is not a substitute for professional medical advice, diagnosis, or treatment.
    </p>
</body>
</html>
